# Generated by Django 3.0 on 2021-11-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customApp', '0002_auto_20211122_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hierarchy',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Admin', 'Admin'), ('Editor', 'Editor'), ('Person', 'Person')], null=True),
        ),
    ]
