# Generated by Django 3.0 on 2021-11-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customApp', '0003_profile_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hierarchy',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Editor', 'Editor'), ('Person', 'Person')], default='', max_length=50, null=True),
        ),
    ]
